import math

SIZE = 30
FIELD_WIDTH, FIELD_HEIGHT = 30, 30
DISPLAY = DW, DH = FIELD_WIDTH * SIZE, FIELD_HEIGHT * SIZE
FPS = 60


COLOR_GROUND = "black"
COLOR_SNAKE_HEAD = "orange"
COLOR_SNAKE_BODY = "yellow"
COLOR_FOOD = "red"


field = [[0] * FIELD_WIDTH for _ in range(FIELD_HEIGHT)]